bounswe/bounswe2025group9

README.md
Added team members to the README.md
=> doc: add team members section to the README.md

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/generic-task.md
- Include a "Reviewers" section for better tracking
- Add relevant emojis for improved readability
- Ensure consistency across all templates
=> chore: add reviewers header and emojis to issue templates

frontend/src/App.tsx, frontend/src/pages/forum/CreatePost.tsx, frontend/src/pages/forum/Forum.tsx, frontend/src/pages/forum/PostDetail.tsx
Added pagination, like button functionality, a separate "add post" page to choose from recipes and nutrition tips, post details page, comment visibility and functionality.
Fixes #142
=> feat: #142 Improving forum 

frontend/README.md, frontend/package-lock.json, frontend/package.json, frontend/src/pages/Home.test.tsx, frontend/src/test/setup.ts, frontend/vitest.config.ts
This PR sets up the testing infrastructure for the frontend using Vitest and React Testing Library, along with example tests for the Home page component.
- Added Vitest configuration in `vitest.config.ts`
- Set up test environment with Jest DOM matchers
- Created test setup file with necessary imports
- Added example tests for Home page component
- Updated package.json with test scripts
- Added comprehensive testing documentation in README.md
- Vitest for test running
- React Testing Library for component testing
- Jest DOM for DOM-specific assertions
- MSW for API mocking in tests
Added example tests for the Home page component that cover:
- Basic rendering of all elements
- Navigation link verification
- Button styles and classes
- Responsive layout testing
Added detailed testing …
=> Add Vitest setup and example test

frontend/src/lib/apiClient.ts, frontend/src/mocks/handlers.ts, frontend/src/pages/forum/CreatePost.tsx, frontend/src/pages/forum/Forum.tsx, frontend/src/pages/forum/PostDetail.tsx
- Posts and foods that are used in the recipe ingredients are now fetched using mock API requests and created like count stability between post details and forum sections for posts: [feat: fetching posts and foods using mock API requests](https://github.com/bounswe/bounswe2025group9/commit/eceb4cf040766a55e0429939f62c0420ca4f0dbc)
- Added a new API endpoint to create new posts: [feat: added new POST API endpoint to create new posts](https://github.com/bounswe/bounswe2025group9/commit/b53efa5206119dbf34c1f6d40b872a0a576815c1)
- Instead of a sole dropdown menu to select the ingredients from, users can now search for an ingredient to add from the current foodbase: 
[feat: users can now search for ingredients to add in the recipe](https://github.com/bounswe/bounswe2025group9/commit/808e12af8bd …
=> Improvements to the forum section

mobile/nutrihub/App.tsx, mobile/nutrihub/package-lock.json, mobile/nutrihub/package.json, mobile/nutrihub/src/components/common/FeatureCard.tsx, mobile/nutrihub/src/components/common/PrimaryButton.tsx, mobile/nutrihub/src/components/food/FoodItem.tsx, mobile/nutrihub/src/components/forum/ForumTopic.tsx, mobile/nutrihub/src/constants/theme.ts, mobile/nutrihub/src/context/AuthContext.tsx, mobile/nutrihub/src/navigation/AppNavigator.tsx, mobile/nutrihub/src/navigation/MainTabNavigator.tsx, mobile/nutrihub/src/navigation/types.ts, mobile/nutrihub/src/screens/FoodScreen.tsx, mobile/nutrihub/src/screens/ForumScreen.tsx, mobile/nutrihub/src/screens/HomeScreen.tsx, mobile/nutrihub/src/screens/LoginScreen.tsx
This PR implements the initial UI structure and basic layout for the core screens of the Nutrihub mobile application: Login, Home, Forum, and Food. It builds upon the navigation structure previously set up and provides the visual foundation for these key areas.
Fixes #157 
* **HomeScreen UI:** Implemented the basic layout for the HomeScreen, taking inspiration from the frontend design. Refactored UI elements into reusable components located `src/components/common/`.
* **LoginScreen UI:** Added `TextInput` components for email/password and basic styling. Added a simple authentication management
* **ForumScreen UI:** Implemented a basic layout using to display placeholder/hardcoded forum post data
* **FoodScreen UI:** Implemented a basic layout using to display placeholder/hardcoded food …
=> feat #157 Implemented the basic UI's for the app screens

mobile/nutrihub/App.tsx, mobile/nutrihub/src/components/common/FeatureCard.tsx, mobile/nutrihub/src/components/common/PrimaryButton.tsx, mobile/nutrihub/src/components/food/FoodItem.tsx, mobile/nutrihub/src/components/forum/ForumTopic.tsx, mobile/nutrihub/src/constants/theme.ts, mobile/nutrihub/src/context/ThemeContext.tsx, mobile/nutrihub/src/navigation/AppNavigator.tsx, mobile/nutrihub/src/navigation/MainTabNavigator.tsx, mobile/nutrihub/src/screens/FoodScreen.tsx, mobile/nutrihub/src/screens/ForumScreen.tsx, mobile/nutrihub/src/screens/HomeScreen.tsx, mobile/nutrihub/src/screens/LoginScreen.tsx
Fixes #165 
* Adds a toggle button component (or integrates with an existing UI library component).
* Implements state management for tracking the current theme (light/dark).
* Applies basic theme styles (e.g., background colors, text colors) that change based on the selected theme.
**Changes Made:**
* Created/updated `ThemeToggleButton` component.
* Added theme context/provider or updated state management logic for theme state.
* Defined basic light and dark theme color palettes/variables.
* Applied theme variables to relevant base components/screens.
* Added the toggle button to the appropriate location in the UI (e.g., Settings screen, Header).
**Reviewer Notes:**
* Please verify the placement and appearance of the toggle button.
* Check if the theme state changes are correctly …
=> Implemented theme toggle button for light/dark modes

frontend/src/pages/auth/Login.tsx, frontend/src/pages/auth/Signup.tsx
I have updated login and signup pages, please review it.
=> feat: added login and signup pages

backend/Dockerfile
This PR modifies the Dockerfile to automatically populate the food database during container startup. This ensures that the food database is properly initialized before the Django server starts running.
Closes #208
=> feat: added db population into dockerfile

backend/api/db_initialization/foods.json, backend/api/db_initialization/nutrition_score.py
Calculated the nutrition scores using nutrition_score.py and updated the foods.json file accordingly.  According for the script to not create duplicates in the database for every image creation, the data is directly updated.
=> Calculating the nutrition scores

mobile/nutrihub/package-lock.json, mobile/nutrihub/package.json, mobile/nutrihub/src/components/food/FoodDetailModal.tsx, mobile/nutrihub/src/components/food/FoodFilterModal.tsx, mobile/nutrihub/src/components/food/ProposeFoodModal.tsx, mobile/nutrihub/src/screens/food/FoodScreen.tsx
This PR enhances the Food Catalog screen by adding comprehensive filtering capabilities, detailed food information modals, and a food proposal submission feature. These improvements provide users with better ways to explore and contribute to the food database. Fixes #206.
- **FoodDetailModal**: Displays comprehensive nutrition information when a food item is selected
- **FoodFilterModal**: Allows users to filter foods by category, dietary options, price, and nutrition score
- **ProposeFoodModal**: Enables users to submit new food proposals for review
- **SuccessNotification**: Provides feedback for successful actions
- Added pull-to-refresh functionality
- Implemented loading states
- Added active filter indicators
- Improved empty state messaging
- Added layout toggle (grid/list views)
- …
=> feat #206 Improving Food Catalog Screen

mobile/nutrihub/App.tsx, mobile/nutrihub/src/components/forum/ForumPost.tsx, mobile/nutrihub/src/constants/forumConstants.ts, mobile/nutrihub/src/context/PostsContext.tsx, mobile/nutrihub/src/navigation/MainTabNavigator.tsx, mobile/nutrihub/src/navigation/types.ts, mobile/nutrihub/src/screens/forum/CreatePostScreen.tsx, mobile/nutrihub/src/screens/forum/ForumScreen.tsx, mobile/nutrihub/src/screens/forum/PostDetailScreen.tsx, mobile/nutrihub/src/types/types.ts
This PR implements the Community Forum screen with full functionality for creating posts, viewing discussions, and interacting with content through likes and comments. The forum enables users to share nutrition tips, recipes, and engage in health-related discussions. Fixes #211.
- **PostDetailScreen**: Displays full post content with comments section and interaction capabilities
- **CreatePostScreen**: Allows users to create different types of posts (Nutrition Tips, Recipes)
- **ForumPost**: Reusable component for displaying forum posts with like/comment functionality
- **PostsContext**: Global state management for forum posts (prepared for API integration)
- Comment system with add/like capabilities
- Post type selection with visual indicators
- Form validation with error messaging
- …
=> feat #211 Improving Food Catalog Screen

backend/api/db_initialization/scraper.py, backend/requirements-dev.txt
Add food image url in  food entries from external API.
=> Scrape food image

backend/api/db_initialization/foods.json, backend/api/db_initialization/load_food_data.py, backend/api/db_initialization/nutrition_score.py, backend/api/db_initialization/scraper.py
I have changed nutrition calculation with a simpler version depending on our requirements, and I added foods.json with image_urls if exists and nutrition scores
=> image urls and nutrition scores have been added

backend/api/db_initialization/load_food_data.py
=> fix image url db insertion

backend/requirements-dev.txt, backend/requirements.txt
Moved library imports from requirements-dev.txt to requirements.txt which causes app does not run.
=> move imports

frontend/src/context/AuthContext.tsx, frontend/src/lib/apiClient.ts
i connected frontend logout functionality with backend logout endopoint, in order to ensure consistency and delete existing jwt tokens.
closes #254
=> feat: connected log out functionality with backend logout endpoint

mobile/nutrihub/src/components/forum/ForumPost.tsx, mobile/nutrihub/src/components/forum/ForumRules.tsx, mobile/nutrihub/src/components/forum/ForumTopic.tsx, mobile/nutrihub/src/config/index.ts, mobile/nutrihub/src/context/PostsContext.tsx, mobile/nutrihub/src/navigation/types.ts, mobile/nutrihub/src/screens/forum/CreatePostScreen.tsx, mobile/nutrihub/src/screens/forum/ForumScreen.tsx, mobile/nutrihub/src/screens/forum/PostDetailScreen.tsx, mobile/nutrihub/src/services/api/client.ts, mobile/nutrihub/src/services/api/forum.service.ts, mobile/nutrihub/src/types/types.ts
This PR replaces the mock data with real API endpoints NutriHub forum features. It implements a dedicated service layer, updates screens and context providers to use live data, adds tag-based filtering, enhances error handling, and completes API client methods. These changes make the forum fully functional—supporting viewing, creating, filtering, updating, and deleting posts, as well as loading comments and tags from the backend. Fixes #270. Some of the UI features are not complete, we can fix it in a future PR.
* **`src/services/api/forum.service.ts`**
* New service layer handling all forum-related API calls.
* Data transformation between API and app models.
* Support for endpoints in the postman collection
* **`src/services/api/client.ts`**
* Added `PATCH` and `DELETE` methods alongside …
=> Feat/270 Backend-integration-for-forum-screen

frontend/src/test/App.test.tsx, frontend/src/test/README.md, frontend/src/test/components/Footer.test.tsx, frontend/src/test/components/Logo.test.tsx, frontend/src/test/components/MainLayout.test.tsx, frontend/src/test/components/Navbar.test.tsx, frontend/src/test/components/ProtectedRoute.test.tsx, frontend/src/test/components/ThemeToggle.test.tsx, frontend/src/test/pages/Home.test.tsx, frontend/src/test/pages/auth/Login.test.tsx, frontend/src/test/pages/auth/Signup.test.tsx, frontend/src/test/pages/foods/Foods.test.tsx, frontend/src/test/pages/forum/Forum.test.tsx
This PR creates and organizes frontend tests into a proper directory structure. It moves all tests from component/page directories into a dedicated test directory with appropriate organization.
-which:
1. Validates test files are properly organized in the test directory structure
2. Checks for proper imports and paths in all test files
3. Falls back to fixing type errors in test files:
- Calls `useAuth` → returns proper UserResponse type
- Calls `apiClient.signup` → returns proper SignupResponse type
- Scrapes & persists test files with proper organization
* `src/test/`
- Added proper test directory structure with components and pages subdirectories
- Fixed type errors in test files
- Organized tests to mirror the source code structure
* `src/pages/`
- Removed test files from component …
=> Frontend tests have been created and organized into a proper directory structure

backend/352.postman_collection.json
This PR updates the Postman collection with the following improvements:
Removed broken endpoints
Updated API URLs to match the current implementation
Reviewer:
@y4z1c1
=> docs: Update Postman collection with improved documentation and URL fixes

frontend/src/test/pages/foods/Foods.test.tsx
=> Fix unused variable

frontend/.gitignore, frontend/src/components/Navbar.tsx, frontend/src/styles/components.css
This PR adds responsive design improvements to the Navbar component, enhancing the mobile experience while maintaining desktop functionality.
- Added a burger menu for mobile screens
- Changed layout to use 2 columns on mobile devices and 3 columns on desktop
- Implemented proper theme support (light/dark mode) for the mobile menu
- Vertically aligned theme toggle and burger menu icons for better visual consistency
- Positioned burger menu and theme toggle to the right side of the navbar
<div align="center">
<p><em>Mobile navbar view</em></p>
<p><em>Mobile burger menu open</em></p>
<p><em>Light theme navbar</em></p>
<p><em>Default navbar</em></p>
</div>
closes #301
=> fix: beautify navbar for mobile screens

README.md, frontend/.env
This PR enhances the README by adding the Nutrihub logo with a link to our website (nutrihub.fit).
Changes:
* Added Nutrihub logo image
* Added link to nutrihub.fit website
* Improved visual appeal of the README
Reviewer:
@ArdaSaygan
=> docs: Add Nutrihub logo and website link to README

backend/api/db_initialization/scraper.py
Setting those variables empty is bad practice
=> Fetch FatSecret keys from env

frontend/src/components/Footer.tsx
added android apk download link to the footer
=> feat: add apk link to the footer

backend/foods/urls.py, backend/foods/views.py
This feature adds a new API endpoint to fetch nutrition facts for a specified food item using the [Open Food Facts API](https://world.openfoodfacts.org/).
---
- Accepts a query parameter `name` representing the food item.
- Makes a GET request to the Open Food Facts API with the provided name.
- Extracts nutritional information such as:
- **Calories** (`energy-kcal_100g`)
- **Protein** (`proteins_100g`)
- **Fat** (`fat_100g`)
- **Carbohydrates** (`carbohydrates_100g`)
- **Fiber** (`fiber_100g`)
- Returns a JSON response with the extracted data or a warning if no product is found.
=> Fetch Nutrition Information from Open Food Facts API
